### ISSUE TITLE
Upscale PNG 16bit

### ISSUE THREAD

**Issue by paulwinex** [TheMrKingent/NeuralUpscale#1]
Hi
I want to upscale PNG sequence with 16 bit color depth. NeuralUpscale works just fine, but output image is 8bit. How to upscale and save 16 bit?

**Comment by TheMrKingent** [comment]
I believe the issue you are facing is due to Tensorflow's `img_to_array()` and `array_to_img()` (both used in NeuralUpscale) forcing the output image to be converted to an underlying 8-bit encoded tensor. Also, PIL is notoriously annoying when dealing with non-8-bit images. Luckily, the models at their core work with 0-1 scaled float32 tensors, which means they do not depend on how the image is originally encoded, nor its encoding once upscaled, therefore, feeding such tensors to the models should be sufficent.

So, my suggestion would be to import the image into Python using wathever package works best for you, and coverting the image to a numpy array. Then, assuming the array is encoded as 0-65535 integers, scaling it to 0-1 floats, and feeding it to the model.

Using the RGB model, the pipeline would be something like this: (I'm just dropping the whole upscaler interface for convenience)

```python
# Model input pipeline
inp_array = inp_array / 65535
inp_array = np.expand_dims(inp_array, axis=0)

# Upscale
out_array = model.predict(inp_array)

# Model output pipeline
out_array = out_array[0]
out_array = out_array * 65535
out_array = out_array.astype(int)
out_array = out_array.clip(0, 65535)
```

Again, the initial `inp_array` and the final `out_array` here are 0-65535 3-channels numpy arrays, you can convert between them and an image data structure as you wish.

As for the upscaling performance of the models for images other than 8-bit encoded, I speculate there would be not much difference in practice, if any at all, between the pre-trained models provided and a specifically trained one for, say, 16-bit upscaling. I do believe however this would be an interesting topic to research.

Thanks for bringing this up, hope it solves.

**Comment by paulwinex** [comment]
Thank you. I will try this method
